services:
  secad:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ./.env
    depends_on:
      - vector-db
    networks:
      - ragnet
  
  vector-db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      LANG: en_US.utf8
      LANGUAGE: en_US:en
      LC_ALL: en_US.utf8
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - ragnet

networks:
  ragnet:
    driver: bridge

